### ISSUE TITLE
Livefeed: layout changes sharply when scrolling in a narrow Safari window

### ISSUE THREAD

**Issue by JakubAdamBukaj** [guardian/frontend#8399]
Steps to reproduce:

1. Open http://www.theguardian.com/business/blog/live/2015/feb/20/eurozone-ministers-gather-for-crucial-greece-talks-live-updates in a Chrome window that is fairly narrow (say ~400px).
2. Scroll down.
3. See the "Key events" section suddenly collapse as you reach a certain point.

Here's a screencast that will shed more light: https://vid.me/Qc7M

**Comment by ScottPainterGNM** [comment]
Hi @jakub- I'm having trouble with replicating this issue, could you advise of your browser version and operating system please?

**Comment by jakub-** [comment]
@ScottPainterGNM Having trouble reproducing it in Chrome but I am able to in Safari 8.0.2, Yosemite. This may very well be a WebKit bug that's been fixed in Chrome since.

**Comment by ScottPainterGNM** [comment]
Thanks @jakub- I have replicated this in Safari 8.0.5 also.

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now

**Comment by JakubAdamBukaj** [comment]
I will offer my feedback and encourage you to rethink your GitHub practices. Closing bugs that haven't been fixed is not only bad internal accounting, but also rather disrespectful to people who spend their free time „QAing” your website, by the virtue of reporting bugs they randomly run into when using TG, naturally. Now, of course the help was unsolicitied – so no hard feelings here at all – but ironically, so is the socialdemocratic welfare state that the newspaper's been defending, so perhaps your leftist position would also align with a well-behaved open source community workflow.

An open issue doesn't cost anything, a closed one costs you the risk of being unable to remember its existence and other people being unable to find a record thereof.

**Comment by johnduffell** [comment]
Hi, we do appreciate your feedback and with our extremely limited development resource we can only do a little.  Unfortunately we have allowed a backlog to build up in the past and in reality we didn't fix all these issues and wouldn't have got to them any time soon.  We have rethought our practices and made a team to deal with maintenance and deal with current issues, but we have to be honest and say which issues we can and can't fix.  Really the problem with our github practice was that we didn't get back to you straight away with feedback.  I hope you understand, and as a final comment in keeping with our open ideals, we would appreciate contributions.  Or, if you would like to come and work for us, we do have some openings in the team!  I'm hope this addresses your concerns in some way, and I hope you are generally satisfied with our work.

**Comment by JakubAdamBukaj** [comment]
OK, this is totally reasonable! Thanks for the detailed follow-up. :)
